name: Auto Update Bing Images CI

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"
  push:
    branches: [ gh-pages ]
  pull_request:
    branches: [ gh-pages ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # checkout
    - name: checkout
      uses: actions/checkout@v4
      with:
        persist-credentials: false # 避免凭据冲突
        fetch-depth: 0 # 确保有完整的提交历史

    # setup nodejs and cache dependencies
    - name: Use Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    # Run the script to update images.json
    - name: Update Bing images
      run: node ./assets/js/bing.js

    # commit
    - name: commit file
      run: |
        git config --local user.email 'github-actions[bot]@users.noreply.github.com'
        git config --local user.name 'github-actions[bot]'
        git diff --exit-code || git add . && git commit -am '[bot] update images.json' --allow-empty
    # push   
    - name: Commit and Push changes
      uses: EndBug/add-and-commit@v9
      with:
        add: '.'
        message: '[CI] Auto-update images.json'
        pull: 'false'
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}