name: Auto Update Bing Images CI

on:
  workflow_dispatch:
  schedule:
    - cron: "0 1 * * *"  # 每天 UTC 时间凌晨1点运行
  push:
    branches: [ gh-pages ]
  pull_request:
    branches: [ gh-pages ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    # 1. 检出代码
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        # 关键：禁用 checkout 提供的凭据，避免与后续步骤冲突
        persist-credentials: false
        # 获取完整的提交历史，确保 git diff 和 push 正常工作
        fetch-depth: 0

    # 2. 设置 Node.js 环境
    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20.x'

    # 3. 运行您的 bing.js 脚本
    # 这个脚本应该会修改 assets/json/images.json 文件
    - name: Run bing.js script
      run: node ./assets/js/bing.js

    # 4. 提交并推送更改
    # 使用 EndBug/add-and-commit，这是目前最推荐的方案
    - name: Commit and Push changes
      uses: EndBug/add-and-commit@v9
      with:
        # 添加所有更改的文件
        add: '.'
        # 提交信息
        message: '[CI] Auto-update Bing images.json'
        # 不在推送前执行 git pull (因为我们已经用 fetch-depth: 0 获取了完整历史)
        pull: 'false'
      # 将您的 GH_TOKEN 作为 GITHUB_TOKEN 环境变量提供给这个 Action
      env:
        GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}